name: Build ICS (What’s On)

on:
  workflow_dispatch: {}
  push:
    paths:
      - scripts/**
      - data/**
      - .github/workflows/build-ics.yml
      - requirements.txt

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo tree
        run: |
          echo "== repo root ==" && ls -la
          echo "== scripts ==" && ls -la scripts || true
          echo "== data ==" && ls -la data || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          set -x
          python -V
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze

      - name: Validate YAML (warn only)
        run: |
          python - <<'PY'
          import os, yaml
          p = "data/events.yaml"
          if not os.path.exists(p):
              print(f"[warn] missing: {p}")
          else:
              try:
                  yaml.safe_load(open(p, encoding="utf-8"))
                  print(f"[ok] parsed: {p}")
              except Exception as e:
                  print(f"[warn] YAML parse issue in {p}: {e}")
          PY

      - name: Build ICS
        run: |
          set -x
          python scripts/build_ics.py

      - name: Count events (fail if zero)
        run: |
          if [ ! -f whatson-shropshire-cheshire-northwales.ics ]; then
            echo "::error::ICS file not found at repo root."
            exit 1
          fi
          COUNT=$(grep -c '^BEGIN:VEVENT' whatson-shropshire-cheshire-northwales.ics || echo 0)
          echo "VEVENT count: ${COUNT}"
          if [ "$COUNT" -eq 0 ]; then
            echo "::error::ICS contains zero events."
            exit 1
          fi

      - name: Sanity-check ICS (no empty props)
        run: |
          # Fail if Apple-hostile empty properties exist
          if grep -nE '^(URL|CATEGORIES|DESCRIPTION):\s*$' whatson-shropshire-cheshire-northwales.ics; then
            echo "::error::Found empty ICS properties (URL/CATEGORIES/DESCRIPTION). Fix build_ics.py."
            exit 1
          fi
          echo "ICS basic sanity checks passed."

      - name: Upload ICS artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: whatson-ics
          path: whatson-shropshire-cheshire-northwales.ics

      - name: Commit & push (resilient)
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add whatson-shropshire-cheshire-northwales.ics || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "auto: build ICS"
          if git push origin HEAD:main; then
            exit 0
          fi
          echo "Push rejected; rebasing…"
          git pull --rebase origin main || true
          git push origin HEAD:main || git push --force-with-lease origin HEAD:main
